Creating 1D Array.

In [2]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
print(arr.ndim)

1


In [5]:
print(arr.shape)

(3,)


In [6]:
print(arr.dtype)

int32


In [7]:
print(arr.itemsize)

4


In [9]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr.ndim) # ndim tells the dimension of array

2


In [11]:
print(arr.shape)  # shape tells the no. of rows and columns in an array

(2, 3)


In [12]:
print(arr.dtype)

int32


In [13]:
print(arr.itemsize)

4


In [14]:
arr=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [15]:
arr=np.array([[[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]], [[1,2,3],[4,5,6]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [16]:
print(arr.ndim)

3


In [17]:
print(arr.shape) # 3= 3 dimensional, 2= 2 elements in each, 3= 3 columns in each

(3, 2, 3)


In [18]:
arr=np.array([[[1.5,2.5,3.5]], [[10.0,20.5,30]]])
print(arr)

[[[ 1.5  2.5  3.5]]

 [[10.  20.5 30. ]]]


In [19]:
print(arr.ndim)

3


In [20]:
print(arr.shape)

(2, 1, 3)


Shape tells us the number of elements in each dimension of an array arr[axis0, axis1, axis2]

In [21]:
arr=np.array([[[1,2,3,1], [4,5,6,1], [7,8,9,1]], [[10,20,30,1], [40,50,60,1], [7,8,9,1]]])
print(arr)

[[[ 1  2  3  1]
  [ 4  5  6  1]
  [ 7  8  9  1]]

 [[10 20 30  1]
  [40 50 60  1]
  [ 7  8  9  1]]]


In [22]:
print(arr.ndim)

3


In [23]:
print(arr.shape)

(2, 3, 4)


Create 2 matrices and take their transpose and add them.

In [25]:
matrix=np.array([[1,2,3], [4,5,6]])

In [26]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [33]:
matrix1=np.array([[1,2,3], [4,5,6]])
matrix2=np.array([[10,20,30], [40,50,60]])

In [34]:
print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]


In [35]:
print(matrix1.T)

[[1 4]
 [2 5]
 [3 6]]


In [36]:
print(matrix1.shape)

(2, 3)


In [37]:
print(matrix1.T.shape)

(3, 2)


In [38]:
matrix3 = matrix1 + matrix2

In [39]:
print(matrix3)

[[11 22 33]
 [44 55 66]]


In [40]:
matrix3 = matrix1 - matrix2

In [41]:
print(matrix3)

[[ -9 -18 -27]
 [-36 -45 -54]]


In [42]:
vector=np.array([10,11,12])

In [43]:
print(vector)

[10 11 12]


In [44]:
print(vector.T)

[10 11 12]


In [45]:
arr2=np.array([[[1,2,3,4,5],[4,5,6,7]],[[8,9,10,11],[10,20,30,12]],[[40,50,60,70],[70,80,90,100]]])
print(arr2)

[[list([1, 2, 3, 4, 5]) list([4, 5, 6, 7])]
 [list([8, 9, 10, 11]) list([10, 20, 30, 12])]
 [list([40, 50, 60, 70]) list([70, 80, 90, 100])]]


In [46]:
print(arr2.shape)

(3, 2)


In [47]:
print(arr2.dtype)

object


In [48]:
print(arr2.ndim)

2


In [49]:
print(arr2.size)

6


In [50]:
print(arr2.itemsize)

8


In [19]:
array2=np.array([[1,2,3],[3,4,5],[7,8,0]])

In [52]:
print(array2)

[[1 2 3]
 [3 4 5]
 [7 8 0]]


In [53]:
print(array2.mean)

<built-in method mean of numpy.ndarray object at 0x000000B9E04071C0>


In [54]:
print(np.mean(array2))  # Default mean gives the mean of all elements and mean of all elementsin 2d array

3.6666666666666665


In [55]:
print(np.mean(array2, axis=0))   # It finds the mean of each column 

[3.66666667 4.66666667 2.66666667]


In [56]:
print(np.mean(array2, axis=1))    # It finds the mean of each row

[2. 4. 5.]


In [60]:
array2=np.array([[1,2,3],[3,4,5],[7,8,0]])   # Created a 2d array
print("mean columnwise")
print(np.mean(array2, axis=0))   # mean columnwise
print("std columnwise")
print(np.std(array2, axis=0))   # Standard deviation
print("var columnwise")
print(np.var(array2, axis=0))   # Variance
print("max columnwise")
print(np.max(array2, axis=0))   # maximum of each column
print("min columnwise")
print(np.min(array2, axis=0))   # minimum of each column
print("sum columnwise")
print(np.sum(array2, axis=0))   # adds elements of matrix columnwise
print("prod columnwise")
print(np.prod(array2, axis=0))  # product of elements in each column

mean columnwise
[3.66666667 4.66666667 2.66666667]
std columnwise
[2.49443826 2.49443826 2.05480467]
var columnwise
[6.22222222 6.22222222 4.22222222]
max columnwise
[7 8 5]
min columnwise
[1 2 0]
sum columnwise
[11 14  8]
prod columnwise
[21 64  0]


In [61]:
array2.sum(axis=0)

array([11, 14,  8])

In [20]:
np.sum(array2,axis=0)

array([11, 14,  8])

In [21]:
np.any(array2,axis=0)

array([ True,  True,  True])

In [22]:
np.any(array2)

True

In [24]:
print(array2)

[[1 2 3]
 [3 4 5]
 [7 8 0]]


In [25]:
np.any(array2)

True

In [27]:
array2.any(axis=0)

array([ True,  True,  True])

In [28]:
array2.all(axis=0)

array([ True,  True, False])

In [29]:
array2=np.array([[1,2,3], [3,4,5], [7,9,0]])
print(array2)

[[1 2 3]
 [3 4 5]
 [7 9 0]]


In [30]:
array2.all(axis=0)

array([ True,  True, False])

In [31]:
array2.all()

False

In [32]:
array2=np.array([[1,2,3], [3,4,5], [7,9,10]])
print(array2)

[[ 1  2  3]
 [ 3  4  5]
 [ 7  9 10]]


In [35]:
array2.any(axis=0)   #

array([False,  True,  True])

In [33]:
array2=np.array([[0,2,3], [0,4,5], [0,9,0]])
print(array2)

[[0 2 3]
 [0 4 5]
 [0 9 0]]


In [34]:
array2.any(axis=0)   # if a column has all zeros , it returns false

array([False,  True,  True])

Array Indexing Slicing Updating

In [5]:
arr=np.array[1,2,4,5,6]
print(arr)
print(arr[0], arr[2])  # Access elements of 1d array
print(arr[2:4])  # Access element 2 and 3 ends with 1 less
print(arr[2:5])
print(arr[:5])   # Starts from 0 to 4
print(arr[2:])   # Starts  from 2 till end
arr[2]=200       # array Updation
print(arr)   

[1, 2, 4, 5, 6]
1 4
[4, 5]
[4, 5, 6]
[1, 2, 4, 5, 6]
[4, 5, 6]
[1, 2, 200, 5, 6]


Accessing Slicing and Updation 2D array

In [16]:
arr=np.array([[1,2,4,5,6], [1.2,1.4,2.4,5.6,6.7]])
print(arr)
print(arr[1][1], arr[0][2])  # Access elements of 2d array
print(arr[0], arr[1])
#print(arr[slicing of row,slicing of column])
print(arr[1:2,  2:4])  # Access element 2 and 3 ends with 1 less
print(arr[:, 1:2])
print(arr[1:3,  3:])
print(arr[1:, 2:])
arr[1,4]=500  # Array Updation
print(arr)
#print(arr[2:5])
#print(arr[:5])   # Starts from 0 to 4
#print(arr[2:])   # Starts  from 2 till end
#arr[2]=200       # array Updation
#print(arr)   

[[1.  2.  4.  5.  6. ]
 [1.2 1.4 2.4 5.6 6.7]]
1.4 4.0
[1. 2. 4. 5. 6.] [1.2 1.4 2.4 5.6 6.7]
[[2.4 5.6]]
[[2. ]
 [1.4]]
[[5.6 6.7]]
[[2.4 5.6 6.7]]
[[  1.    2.    4.    5.    6. ]
 [  1.2   1.4   2.4   5.6 500. ]]


In [40]:
arr1=np.array([[1,2,3,5,6],[6,7,8,9,7],[12,14,45,66,7],[44,55,67,55,7]])
print(arr1)
print(arr1[0:3, 0:3])

[[ 1  2  3  5  6]
 [ 6  7  8  9  7]
 [12 14 45 66  7]
 [44 55 67 55  7]]
[[ 1  2  3]
 [ 6  7  8]
 [12 14 45]]


In [2]:
# Create array from list
import numpy as np
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)   # Send list1 as a parameter to an array
print(arr)

[1 2 3 4 5]


In [5]:
# Using arange function of numpy
import numpy as np
arr = np.arange(10,100)   # Arrange (start, stop, step)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [6]:
# Using arange function of numpy
import numpy as np
arr = np.arange(4,10,2)   # Arrange (start, stop, step)
print(arr)

[4 6 8]


In [7]:
# Creating Array with Zeros where is it useful
import numpy as np
zero_arr = np.zeros((5,5))   # Arrange (start, stop, step)
print(zero_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# Creating Array with ones where is it useful
import numpy as np
ones_arr = np.ones((4,3))   # Arrange (start, stop, step)
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# Array of given size filled with value 2.5
full_array = np.full((4,3), 2.5)   # Arrange (start, stop, step)
print(full_array)

[[2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]
 [2.5 2.5 2.5]]


How to create 2D array using range?

In [10]:
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr=np.arange(0,10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
arr=np.arange(0,12).reshape(2,3)
print(arr)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [16]:
arr=np.arange(0,12).reshape(2,3,2)
print(arr)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [19]:
arr=np.arange(0,12).reshape(2,3,2).ravel()
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [20]:
# Creating array using linspace
import numpy as np
vector = np.linspace(0, 20, 5)
print(vector)
# Observe the difference between linspace and arange

[ 0.  5. 10. 15. 20.]


In [21]:
# Creating array using linspace
import numpy as np
vector = np.linspace(0, 20, 3)   # linspace(start, stop, number of values)
print(vector)
# Observe the difference between linspace and arange

[ 0. 10. 20.]


In [22]:
# Creating array using linspace
import numpy as np
vector = np.linspace(0, 20, 8)   # linspace(start, stop, number of values)
print(vector)
# Observe the difference between linspace and arange

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [24]:
# A 3x3 Array of random values uniformly distributed between 0 and 1
ran_arr = np.random.random((3,3))
print(ran_arr)

[[0.0614826  0.66498737 0.36458886]
 [0.79719181 0.37554259 0.70670443]
 [0.45623349 0.12747342 0.84051389]]


In [25]:
# A 3x4 array of random integers in the interval(90,10)
np.random.randint(0, 10, (3, 4))

array([[7, 0, 4, 8],
       [7, 3, 8, 6],
       [5, 7, 6, 5]])

In [4]:
arr21=np.array([[[1,2,3,5],[4,5,6]]])
print(arr21)

[[list([1, 2, 3, 5]) list([4, 5, 6])]]
